config/routes.rb
Rails.application.routes.draw do
  
  root 'schedules#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validate :start_end_check



  private
    # 開始日と終了日の逆転を許可しない
    def start_end_check
      if self.start.present? && self.end.present?
        errors.add(:end, "は開始日より前に設定できません") unless self.start <= self.end
      end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  def index
    #@schedules = Schedule.all
    @q = Schedule.ransack(params[:q]) #ransackを導入してソート機能を実装
    @schedules = @q.result
  end
  
  def new
    @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :end, :all_day, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to schedules_path
    else
      render "new"
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start, :end, :all_day, :memo))
      flash[:notice] = "ID:#{@schedule.id} のスケジュールを更新しました"
      redirect_to schedules_path
    else
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to schedules_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  # boolean型のtrueを"○"に変換"
  def signature(boolean)
    case boolean
    when true
      return "○"
    when false
      return ""
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p><%= "現在の日時 : #{Date.today.strftime("%Y年%-m月%d日")}" %></p>
      <p><%= "スケジュール合計 : #{Schedule.count}" %></p>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>

<div class="error">
  <%= render "shared/error", obj: @schedule %>
</div>

<%= form_with model: @schedule do |f| %>
  <table>
    <tbody>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <th><%= f.label :start ,"開始日" %></th>
        <td><%= f.date_field :start %></td>
      </tr>
      <tr>
        <th><%= f.label :end , "終了日" %></th>
        <td><%= f.date_field :end %></td>
      </tr>
      <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td>
          <%= f.check_box :all_day, :as => :boolean %>
          終日の場合はチェックを入れます
        </td>
      </tr>
      <tr>
        <th><%= f.label :memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :memo %></td>
      </tr>
    </tbody>
  </table>
  
  <div>
    <ul>
      <li><%= f.submit "スケジュールの編集を完了する", class:"button" %></li>
      <li><%= link_to "スケジュール一覧に戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧</h2>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :id, "ID") %></th>
      <th><%= sort_link(@q, :title, "タイトル") %></th>
      <th><%= sort_link(@q, :start, "開始日") %></th>
      <th><%= sort_link(@q, :end, "終了日") %></th>
      <th>終日</th>
      <th><%= sort_link(@q, :updated_at, "スケジュール更新日時") %></th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start.strftime("%Y年%-m月%d日") %></td>
        <td><%= schedule.end.strftime("%Y年%-m月%d日") %></td>
        <td><%= signature(schedule.all_day) %></td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "確認", schedule %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule) %></td>
        <td><%= link_to "削除", schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "スケジュール新規登録", new_schedule_path %></p>

app/views/schedules/new.html.erb
<h2>スケジュール新規作成</h2>

<div class="error">
  <%= render "shared/error", obj: @schedule %>
</div>

<%= form_with model: @schedule do |f| %>
  <table>
    <tbody>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <th><%= f.label :start ,"開始日" %></th>
        <td><%= f.date_field :start %></td>
      </tr>
      <tr>
        <th><%= f.label :end , "終了日" %></th>
        <td><%= f.date_field :end %></td>
      </tr>
      <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td>
          <%= f.check_box :all_day, :as => :boolean %>
          終日の場合はチェックを入れます
        </td>
      </tr>
      <tr>
        <th><%= f.label :memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :memo %></td>
      </tr>
    </tbody>
  </table>
  
  <div>
    <ul>
      <li><%= f.submit "スケジュールを新規登録する", class:"button" %></li>
      <li><%= link_to "スケジュール一覧に戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>



<table>
  <tbody>
    <tr>
      <th>タイトル</th>
      <td><%= @schedule.title %></td>
    </tr>
    <tr>
      <th>開始日</th>
      <td><%= @schedule.start.strftime("%Y年%-m月%d日") %></td>
    </tr>
    <tr>
      <th>終了日</th>
      <td><%= @schedule.end.strftime("%Y年%-m月%d日") %></td>
    </tr>
    <tr>
      <th>終日</th>
      <td><%= signature(@schedule.all_day) %></td>
    </tr>
    <tr>
      <th>スケジュールメモ</th>
      <td><%= @schedule.memo %></td>
    </tr>
  </tbody>
</table>

<p><%= link_to "スケジュール一覧に戻る", schedules_path %></p>
<p><%= link_to "スケジュールを編集する", edit_schedule_path(@schedule) %></p>
<p><%= link_to "スケジュールを削除", @schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %></p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>